sudo add-apt-repository ppa:deadsnakes/ppa;
sudo apt-get update;
sudo apt-get install python3.8;
pip install virtualenv;
source sprites/bin/activate || virtualenv sprites --python=python3.8 && pip install -r requirements_all.txt;
source sprites/bin/activate;
python --version;
pip install seaborn;
export IS_SERVER="True";
pip freeze && python src/trainer.py --tag default --config clevr6.yml;
